### PR TITLE
to_numeric() fun

### PR DESCRIPTION
**Pull request by rosseji**
simple method is to gather...

```
sheet_as_num <- sheet %>%
  gather(Series, Value, Bir.Aus:Per.ERP.Cha.Ove.Pre.Yea.Aus) %>%
  mutate(Value = as.numeric(Value))

str(sheet_as_num)

Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	1859 obs. of  3 variables:
$ Date  : POSIXct, format: "1981-06-01" "1981-09-01" "1981-12-01" "1982-03-01" ...
$ Series: chr  "Bir.Aus" "Bir.Aus" "Bir.Aus" "Bir.Aus" ...
$ Value : num  60.3 61 55 60.6 60.5 60.3 58.6 61.9 61 62 ...
```

But as you really want a function...

```
to_numeric(df, ...)
?to_numeric
```

Example of default usage:
```
sheet %>%
  to_numeric() %>% 
  str()

Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	143 obs. of  14 variables:
$ Date                       : POSIXct, format: "1981-06-01" "1981-09-01" "1981-12-01" "1982-03-01" ...
$ Bir.Aus                    : num  60.3 61 55 60.6 60.5 60.3 58.6 61.9 61 62 ...
$ Dea.Aus                    : num  26.7 31.5 25.7 26.1 27.7 33.9 27.1 25.6 26.4 31.9 ...
$ Nat.Inc.Aus                : num  33.6 29.6 29.3 34.5 32.7 26.4 31.5 36.4 34.6 30.1 ...
$ Int.Arr.Aus                : num  78 76.6 65.9 70.3 81.7 66.9 58.7 57.5 71 62.4 ...
$ Int.Dep.Aus                : num  78 76.6 65.9 70.3 81.7 66.9 58.7 57.5 71 62.4 ...
$ Ove.Arr.Aus                : num  48.2 50 56.7 58.7 45.3 45.6 45.6 47.4 34.1 34.2 ...
$ Ove.Dep.Aus                : num  19.1 19.1 21.7 26.3 20.5 21.2 24.3 29.3 22.5 23.9 ...
$ Net.Per.and.Lon.Ter.Mov.Aus: num  29.1 30.8 35 32.4 24.8 24.4 21.3 18.1 11.6 10.3 ...
$ Mig.Adj.Aus                : num  -3.6 3.3 -0.5 -1 3.3 2.5 -5 1.1 -0.7 3.3 ...
$ Net.Ove.Mig.Aus            : num  25.6 34.1 34.5 31.4 28.1 26.9 16.3 19.2 10.9 13.6 ...
$ Est.Res.Pop.ERP.Aus        : num  14923 14989 15054 15122 15184 ...
$ ERP.Cha.Ove.Pre.Yea.Aus    : num  NA NA NA NA 261 ...
$ Per.ERP.Cha.Ove.Pre.Yea.Aus: num  NA NA NA NA 1.75 1.67 1.56 1.48 1.38 1.31 ...
```

Example of user input:
```
sheet %>%
  to_numeric(Bir.Aus:Ove.Dep.Aus) %>% 
  str()

Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	143 obs. of  14 variables:
  $ Date                       : POSIXct, format: "1981-06-01" "1981-09-01" "1981-12-01" "1982-03-01" ...
$ Bir.Aus                    : num  60.3 61 55 60.6 60.5 60.3 58.6 61.9 61 62 ...
$ Dea.Aus                    : num  26.7 31.5 25.7 26.1 27.7 33.9 27.1 25.6 26.4 31.9 ...
$ Nat.Inc.Aus                : num  33.6 29.6 29.3 34.5 32.7 26.4 31.5 36.4 34.6 30.1 ...
$ Int.Arr.Aus                : num  78 76.6 65.9 70.3 81.7 66.9 58.7 57.5 71 62.4 ...
$ Int.Dep.Aus                : num  78 76.6 65.9 70.3 81.7 66.9 58.7 57.5 71 62.4 ...
$ Ove.Arr.Aus                : num  48.2 50 56.7 58.7 45.3 45.6 45.6 47.4 34.1 34.2 ...
$ Ove.Dep.Aus                : num  19.1 19.1 21.7 26.3 20.5 21.2 24.3 29.3 22.5 23.9 ...
$ Net.Per.and.Lon.Ter.Mov.Aus: chr  "29.1" "30.8" "35" "32.4" ...
$ Mig.Adj.Aus                : chr  "-3.6" "3.3" "-0.5" "-1" ...
$ Net.Ove.Mig.Aus            : chr  "25.6" "34.1" "34.5" "31.4" ...
$ Est.Res.Pop.ERP.Aus        : chr  "14923.3" "14988.7" "15054.1" "15121.7" ...
$ ERP.Cha.Ove.Pre.Yea.Aus    : chr  NA NA NA NA ...
$ Per.ERP.Cha.Ove.Pre.Yea.Aus: chr  NA NA NA NA ...
```

### CODE REVIEW

**Review by aidandmorrison — APPROVED** [review]
looks awesome

**Comment by aidandmorrison** [comment]
I haven't seen using the variable:anothervariable notation as an input to an argument before.  That's really cool.

**Comment by rosseji** [comment]
@aidandmorrison 
It's syntax that can be used in `dplyr` verbs ie:
```
mtcars %>% select(gear:carb)
```
Uses the `quosure` functions underneath to covert unquoted inputs ie `gear` not `"gear"` to variable names... Very useful!

**Pull request merged**
